version: "3.9"
services:
  api:
    image: docker.pkg.github.com/jfoerste/csgobot/csgobot-api:latest
    restart: always
    environment:
      - TRACKER_KEY
      - STEAM_KEY
  bot:
    image: docker.pkg.github.com/jfoerste/csgobot/csgobot-bot:latest
    restart: always
    environment:
      - TOKEN
    depends_on:
      - api
