version: "3.9"
services:
  api:
    restart: always
    build: ./api
    environment:
      - TRACKER_KEY
      - STEAM_KEY
  bot:
    restart: always
    build: ./bot
    environment:
      - TOKEN
    depends_on:
      - api
